CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,20 +12,16 @@ concurrency:
   cancel-in-progress: true
 
 env:
-  ALLOWERRORS: 'false'
   NBCACHE: ".cache"
-  JULIA_NUM_THREADS: 'auto'
-  JULIA_CI: 'true'
-  JULIA_CONDAPKG_BACKEND: 'Null'
-  UV_SYSTEM_PYTHON: 1
 
 jobs:
   setup:
+    permissions:
+      packages: write
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
-      hash: ${{ steps.hash.outputs.value }}
-      ver: ${{ steps.hash.outputs.ver }}
+      hash: ${{ steps.img.outputs.hash }}
     steps:
     - name: Checkout repository
       uses: actions/checkout@v5
@@ -34,40 +30,27 @@ jobs:
       id: setup-python
       with:
         python-version: '3.x'
-        check-latest: true
-    - name: Read Julia version
-      uses: SebRollen/toml-action@v1.2.0
-      id: read_toml
+    - name: Login to ghcr.io
+      uses: docker/login-action@v3
       with:
-        file: 'Manifest.toml'
-        field: 'julia_version'
-    - name: Get environment hash
-      id: hash
+        registry: ghcr.io
+        username: ${{ github.repository_owner	}}
+        password: ${{ github.token }}
+    - name: Get docker image hash
+      id: img
+      run: echo "hash=${{ hashFiles('requirements.txt', 'Project.toml', 'Manifest.toml', 'src/**', '**/env.Dockerfile') }}" >> "$GITHUB_OUTPUT"
+    - name: Build Docker container
+      env:
+        IMG: ghcr.io/${{ github.repository }}:${{ steps.img.outputs.hash }}
       run: |
-        echo "value=${{ hashFiles('Project.toml', 'Manifest.toml', 'src/**') }}" >> "$GITHUB_OUTPUT"
-        echo "ver=${{ runner.os }}-julia-${{ steps.read_toml.outputs.value }}" >> "$GITHUB_OUTPUT"
-    - name: Setup Julia
-      uses: julia-actions/setup-julia@v2
-      with:
-        version: ${{ steps.read_toml.outputs.value }}
-    - name: Cache Julia packages
-      uses: actions/cache@v4
-      id: cache-julia
-      with:
-        path: ~/.julia
-        key: ${{ steps.hash.outputs.ver }}-${{ steps.hash.outputs.value }}
-        restore-keys: |
-          ${{ steps.hash.outputs.ver }}-
-    - name: Install Julia packages
-      if: ${{ steps.cache-julia.outputs.cache-hit != 'true' }}
-      shell: julia --color=yes {0}
-      run: |
-        using Pkg, Dates
-        Pkg.add(["IJulia", "Literate", "Tables", "MarkdownTables", "JSON"])
-        Pkg.activate(".")
-        Pkg.instantiate()
-        Pkg.precompile()
-        Pkg.gc(collect_delay=Day(0))
+        if ! docker manifest inspect "$IMG" >/dev/null 2>&1; then
+            echo "Image not found in registry. Building and pushing..."
+            docker build -f .github/env.Dockerfile -t "$IMG" .
+            docker push "$IMG"
+            echo "Image built and pushed successfully."
+        else
+            echo "Image already exists in the registry."
+        fi
     - name: List notebooks as a JSON array
       id: set-matrix
       run: echo "matrix=$(python -c 'import glob, json; print(json.dumps(glob.glob("**/*.ipynb", root_dir="docs", recursive=True) + glob.glob("**/*.jl", root_dir="docs", recursive=True)))')" >> "$GITHUB_OUTPUT"
@@ -82,6 +65,7 @@ jobs:
     runs-on: ubuntu-latest
     env:
       NB: docs/${{ matrix.notebook }}
+      IMG: ghcr.io/${{ github.repository }}:${{ needs.setup.outputs.hash }}
     steps:
       - name: Checkout
         uses: actions/checkout@v5
@@ -91,42 +75,22 @@ jobs:
         with:
           path: ${{ env.NBCACHE }}
           key: notebook-${{ needs.setup.outputs.hash }}-${{ hashFiles(env.NB) }}
-      - name: Setup Python
-        uses: actions/setup-python@v6
-        id: setup-python
+      - name: Pull docker image
         if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        with:
-          python-version: '3.x'
-          check-latest: true
-      - name: Install the latest version of uv
-        uses: astral-sh/setup-uv@v6
-        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        with:
-          version: "latest"
-      - name: Install Python dependencies
-        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        run: uv pip install -r requirements.txt
-      - name: Read Julia version
-        uses: SebRollen/toml-action@v1.2.0
-        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        id: read_toml
-        with:
-          file: 'Manifest.toml'
-          field: 'julia_version'
-      - name: Setup Julia
-        uses: julia-actions/setup-julia@v2
-        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        with:
-          version: ${{ steps.read_toml.outputs.value }}
-      - name: Restore Julia packages
-        uses: actions/cache/restore@v4
-        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        with:
-          path: ~/.julia
-          key: ${{ needs.setup.outputs.ver }}-${{ needs.setup.outputs.hash }}
+        run: |
+          docker pull ${{ env.IMG }}
+          docker images ${{ env.IMG }}
       - name: Execute notebook
         if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
-        run: julia --project=@. .github/ci.jl
+        run: >
+          docker run -w /tmp -v ${{ github.workspace }}:/tmp
+          -e NB=${{ env.NB }}
+          -e NBCACHE=${{ env.NBCACHE }}
+          ${{ env.IMG }}
+          julia --project=@. .github/ci.jl
+      - name: Claim output notebook
+        if: ${{ steps.nb-cache.outputs.cache-hit != 'true' }}
+        run: sudo chown -R $USER ${{ env.NBCACHE }}
       - name: Convert artifact Name
         id: art
         run: echo "name=$(echo ${{ env.NB }} | sed 's/\//-/g')" >> "$GITHUB_OUTPUT"
@@ -154,6 +118,8 @@ jobs:
         run: cp --verbose -rf ${{ env.NBCACHE }}/docs/* docs/
       - name: Setup Quarto
         uses: quarto-dev/quarto-actions/setup@v2
+      - name: Remove jl files to avoid confusion with jupytext
+        run: find docs/ -type f -name "*.jl" -delete
       - name: Render Quarto Project
         run: quarto render docs --to html
       - name: Upload artifact for GH pages
